function ASH() {
    window.alert("Ash Ketchum, known as Satoshi (サトシ) in Japan, is a fictional character in the Pokémon franchise owned by Nintendo. He is the protagonist of the Pokémon anime and certain manga series as well as on various merchandise related to the franchise. In Japanese, the character is voiced by Rika Matsumoto, and Hana Takeda. In the English dub, he was voiced by Veronica Taylor in the first eight seasons and has been voiced by Sarah Natochenny since season 9. In the Korean dub, he was voiced by Choi Deok-Hui in the first five seasons and first two films, An Hyeon-Seo in Pokémon films 3 through 5, and has been voiced by Lee Seon-ho since season 6 and the sixth Pokémon film.");
}

function INFERNAPE() {
    window.alert("Infernape is a bipedal, primate-like Pokémon that is primarily reddish-brown with sections of white fur on its chest, head, and lower legs. Several gold markings adorn its body: swirled, circular ones on its knees and shoulders flame-shaped ones on the back of its hands, and a stripe around its back that forms two swirls on its chest. On top of its head is a large flame, which is never extinguished. Infernape has an orange, rounded muzzle, long, round ears with blue inside, and a red ridge over its eyes. The eyes themselves are blue with yellow sclerae. There are five blue digits on both its feet and hands, and it has a long tail. This quick Pokémon practices a unique kind of martial art that involves all of its limbs. This style uses fiery punches and kicks as well.");
}

function SCEPTILE() {
    window.alert("Sceptile is a reptilian, bipedal Pokémon. Its neck is somewhat long, and it has two crests on its head. It has semicircular, yellow eyes with red rims. Its lower jaw and a belt-like band across its waist are also red. Along its back, it has two lines running down the middle and two rows of yellow nodules that are described as seeds. Its tail is shaped similar to that of a palm tree's branch. Both of its long arms have two sharp, elongated leaves and three claws. These leaves allow it to use its former signature move, Leaf Blade.As Mega Sceptile, its head crests become more pointed with a round portion missing from the middle. Red marking surrounds its eyes, which become smaller and more narrow. The yellow seeds down its back grow larger. The last pair of seeds turn red, while the pair above it turns orange. Red stripes encircle the base of its tail and run across its lower belly. The leaves on its wrists become more pointed, and the upper ones have red tips and half-circles cut out of the middles. Covering its chest and shoulders are plates of leaves similar to those that form its tail. Mega Sceptile's tail grows longer and develops a red stinger at the tip. Mega Sceptile can cut off a portion of its tail to fire it like a missile at an opponent. Its lost tail will continue regenerating as long as it still has the energy required for Mega Evolution.");
}

function BLAZIKEN() {
    window.alert("Blaziken (/ˈbleɪzɪkɪn/), known in Japan as Bursyamo (バシャーモ, Bashāmo), is a Pokémon species in Nintendo and Game Freak's Pokémon franchise. Created by Ken Sugimori, Blaziken first appeared in the Pokémon anime episode 'Pop Goes the Sneasel' , and later appeared in the video games Pokémon Ruby and Sapphire, subsequent video game sequels, various merchandise, spin-off titles and animated and printed adaptations of the franchise.In the animated film Pokémon: Destiny Deoxys, which takes place in the Hoenn Region, a Blaziken is owned by Rafe. Another character in the Hoenn Region, May, obtains a Torchic, which eventually evolves into Combusken and finally into a Blaziken, while trying to stop Team Rocket from stealing Ash's Pikachu and some other Pokémon. May then uses Blaziken in the Battle Phase against Ash's Sceptile.[8] In the Sinnoh region, May's Blaziken battles alongside Dawn's Piplup in tag battles.[9] A Blaziken appears in Kalos, under the ownership of Blaziken Mask, where it saves Ash and Pikachu after Mega Evolving. A Blaziken is also owned by Gurkinn, the grandfather of Korrina, the fighting type gym leader in Kalos. This Blaziken fights against Korrina's Lucario.");
}
